// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgU3IwvPp_1NeVq-Iba3NdXXdu2BXqaFI',
    appId: '1:917425481113:web:d45c633f02964471095f08',
    messagingSenderId: '917425481113',
    projectId: 'newapp-3071b',
    authDomain: 'newapp-3071b.firebaseapp.com',
    storageBucket: 'newapp-3071b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdEG3IzDBUDvT8rdJ-Ht9XoL6R7tMQGW4',
    appId: '1:917425481113:android:6aba6eca78981a7c095f08',
    messagingSenderId: '917425481113',
    projectId: 'newapp-3071b',
    storageBucket: 'newapp-3071b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNCloJlOsInLDy1VvVaajxWIVhpWWQjKE',
    appId: '1:917425481113:ios:be0cea333532a5b9095f08',
    messagingSenderId: '917425481113',
    projectId: 'newapp-3071b',
    storageBucket: 'newapp-3071b.firebasestorage.app',
    iosBundleId: 'com.example.newsapp',
  );
}
